### ISSUE TITLE
get errors: npm run production 

### ISSUE THREAD

**Issue by kcloze** [voten-co/voten#191]
npm run production

```
> @ production /media/kcloze/8685937c-af42-4319-aa9b-bb123ccd18ba/data/www/github/voten
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

/media/kcloze/8685937c-af42-4319-aa9b-bb123ccd18ba/data/www/github/voten/node_modules/laravel-mix/setup/webpack.config.js:24
let WebpackConfig = require('../src/builder/WebpackConfig');
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at requireConfig (/media/kcloze/8685937c-af42-4319-aa9b-bb123ccd18ba/data/www/github/voten/node_modules/webpack/bin/convert-argv.js:97:18)
    at /media/kcloze/8685937c-af42-4319-aa9b-bb123ccd18ba/data/www/github/voten/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (native)

npm ERR! Linux 4.4.0-96-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "production"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ production script 'cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/kcloze/8685937c-af42-4319-aa9b-bb123ccd18ba/data/www/github/voten/npm-debug.log
```

**Comment by sullyfischer** [comment]
Please leave your `node -v; npm -v;` output.

**Comment by yoginth** [comment]
yoginth@yoginth:~/Desktop/voten$ node -v
v4.7.2
yoginth@yoginth:~/Desktop/voten$ npm -v
3.5.2

**Comment by sullyfischer** [comment]
Yours are waaay outdated. Upgrade please. These are mine:
```v8.1.2
5.0.3```

**Comment by yoginth** [comment]
I Can't Install it on **_Ubuntu_** and this is the **latest version** available on it.

**Comment by kcloze** [comment]
node v4.2.6
npm  v3.5.2

**Comment by sullyfischer** [comment]
@yoginth @kcloze look at mine, please upgrade. 
We are using Ubuntu on our production server, and no, those are not the latest versions.

**Comment by BoKKeR** [comment]
To upgrade you have to add new sources https://joshtronic.com/2017/12/11/upgrade-to-nodejs-8-on-debian-and-ubuntu/
