### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by sullyfischer** [voten-co/voten#279]
https://sentry.io/voten/voten/issues/471370674/

```
TypeError: Cannot read property 'filter' of undefined
  at call (./resources/assets/js/vue-codes.js:105:41)
  at call (./resources/assets/js/vue-codes.js:261:30)
  at call (./resources/assets/js/vue-codes.js:116:18)
...
(6 additional frame(s) were not displayed)
```

**Comment by YoginthS** [comment]
still not fixed for me!

![screenshot](https://user-images.githubusercontent.com/36839013/36772904-24fc9ebc-1c7d-11e8-8543-6fd703e4b874.png)
